  title: John Harakas
  description: Projects, work, and experiments. 
  name: John Harakas
  markdown: kramdown
  permalink: /blog/:year/:month/:day/:title
  baseurl: "/harakasj.github.io" 
  url: "http://harakasj.github.io"
  plugins:
    - jekyll-seo-tag
